using System;
using System.Linq;
using static System.Environment;

namespace Cvte.Compiler.Tests
{
    [CodeTransform("Generic/ActionCommand.cs", RepeatCount = 4)]
    public class Sample : IPlainCodeTransformer
    {
        private const string ToolName = "Cvte.Compiler.Tests";
        private const string ToolVersion = "1.0";

        private static readonly string GeneratedHeader =
            $@"//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:{Environment.Version.ToString(4)}
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#define GENERATED_CODE
";

        private static readonly string GeneratedFooter =
            $@"";

        private static readonly string Generatedattribute =
            $"[System.CodeDom.Compiler.GeneratedCode(\"{ToolName}\", \"{ToolVersion}\")]";

        public string Transform(string originalText, TransformingContext context)
        {
            var genericCount = context.RepeatIndex + 1;
            if (genericCount == 1)
            {
                return originalText;
            }

            var content = originalText
                // 替换泛型。
                .Replace("<out T>", FromTemplate("<{0}>", "out T{n}", ", ", genericCount))
                .Replace("Task<T>", FromTemplate("Task<({0})>", "T{n}", ", ", genericCount))
                .Replace("Func<T, Task>", FromTemplate("Func<{0}, Task>", "T{n}", ", ", genericCount))
                .Replace(" T, Task>", FromTemplate(" {0}, Task>", "T{n}", ", ", genericCount))
                .Replace("(T, bool", FromTemplate("({0}, bool", "T{n}", ", ", genericCount))
                .Replace("var (t, ", FromTemplate("var ({0}, ", "t{n}", ", ", genericCount))
                .Replace(", t)", FromTemplate(", {0})", "t{n}", ", ", genericCount))
                .Replace("return (t, ", FromTemplate("return ({0}, ", "t{n}", ", ", genericCount))
                .Replace("<T>", FromTemplate("<{0}>", "T{n}", ", ", genericCount))
                .Replace("{T}", FromTemplate("{{{0}}}", "T{n}", ", ", genericCount))
                .Replace("(T value)", FromTemplate("(({0}) value)", "T{n}", ", ", genericCount))
                .Replace("(T t)", FromTemplate("({0})", "T{n} t{n}", ", ", genericCount))
                .Replace("(t)", FromTemplate("({0})", "t{n}", ", ", genericCount))
                .Replace("var t =", FromTemplate("var ({0}) =", "t{n}", ", ", genericCount))
                .Replace(" T ", FromTemplate(" ({0}) ", "T{n}", ", ", genericCount))
                .Replace(" t;", FromTemplate(" ({0});", "t{n}", ", ", genericCount))
                // 生成 [GeneratedCode]。
                .Replace("    public interface ", $"    {Generatedattribute}{NewLine}    public interface ")
                .Replace("    public class ", $"    {Generatedattribute}{NewLine}    public class ")
                .Replace("    public sealed class ", $"    {Generatedattribute}{NewLine}    public sealed class ");
            return GeneratedHeader + NewLine + content.Trim() + NewLine + GeneratedFooter;
        }

        private static string FromTemplate(string template, string part, string seperator, int count)
        {
            return string.Format(template,
                string.Join(seperator, Enumerable.Range(1, count).Select(x => part.Replace("{n}", x.ToString()))));
        }
    }
}
